begin
  require 'hen'
rescue LoadError
  abort "Please install the 'hen' gem first."
end

PROGNAME = %q{<%= ask 'Program name' %>}

require File.join('lib', PROGNAME, 'version')

Hen.lay! {{
  :rubyforge => {
    :project => %q{<%= ask 'Rubyforge project name' %>},
    :package => PROGNAME
  },

  :gem => {
    :version      => <%= ask 'Module/Class name' %>::VERSION,
    :summary      => %q{<%= ask 'Program description summary' %>},
    :files        => FileList['lib/**/*.rb'].to_a,
    :extra_files  => FileList['[A-Z]*'].to_a,
    :dependencies => %w[]
  }
}}
