begin
  require 'hen'
rescue LoadError
  abort "Please install the 'hen' gem first."
end

require 'lib/your_prog/version'

task(:doc_spec) {{
  :title => 'your_prog Application documentation'
}}

task(:gem_spec) {{
  :name              => 'your_prog',
  :version           => YourProg::VERSION,
  :rubyforge_project => 'your_project',
  :summary           => 'Your super duper sample prog',
  :files             => FileList['lib/**/*.rb', 'bin/*'].to_a,
  :extra_files       => FileList['[A-Z]*', 'example/*'].to_a,
  :dependencies      => %w[hyper magic]
}}

Hen.lay!
