require %q{lib/<%= ask! "Program's name" %>/version}

begin
  require 'hen'

  Hen.lay! {{
    :rubyforge => {
      :project => %q{<%= ask "Rubyforge project's name (Leave empty for none)" %>},
      :package => %q{<%= ask! "Program's name" %>}
    },

    :gem => {
      :version      => <%= ask! "Module's/Class' name" %>::VERSION,
      :summary      => %q{<%= ask "Program's description summary" %>},
      :files        => FileList['lib/**/*.rb'].to_a,
      :extra_files  => FileList['[A-Z]*'].to_a,
      :dependencies => %w[]
    }
  }}
rescue LoadError
  abort "Please install the 'hen' gem first."
end

### Place your custom Rake tasks here.
