require File.expand_path(%q{../lib/<%= progname %>/version}, __FILE__)

begin
  require 'hen'

  Hen.lay! {{
    :gem => {
      :name         => %q{<%= progname %>},
      :version      => <%= classname %>::VERSION,
      :summary      => %q{<%= progdesc %>},
      :author       => %q{<%= fullname %>},
      :email        => %q{<%= emailaddress %>},
      :license      => %q{AGPL},
      :dependencies => %w[]
    }
  }}
rescue LoadError => err
  warn "Please install the `hen' gem. (#{err})"
end
