require File.expand_path(%q{../lib/<%= progname %>/version}, __FILE__)

begin
  require 'hen'

  Hen.lay! {{
    :gem => {
      :name         => %q{<%= progname %>},
      :version      => <%= classname %>::VERSION,
      :summary      => %q{<%= progdesc %>},
      :files        => FileList['lib/**/*.rb'].to_a,
      :extra_files  => FileList['[A-Z]*'].to_a,
      :dependencies => %w[]
    }
  }}
rescue LoadError => err
  warn "Please install the `hen' gem. (#{err})"
end
